김미서 / 8월 3주차 / 월
SSAFY-10th-Seoul17/algorithm_ssafy pull request #104
Opened 2023-08-14 03:44 UTC by seomiii

---
## 🎈boj 17086 - 아기상어2
<br>

#### 🗨 해결방법 
- 빈칸일 때 bfs를 돌려서 안전거리를 리턴받고, max값을 찾아주어야한다고 생각했습니다. 
- bfs로 퍼져나가면서 count를 저장하는 이차원배열에 거리를 저장해주면서
- 상어를 만났을 경우 이전의 좌표의 count를 리턴하게 했습니다.
<br>

<br>

## 🎈boj 18353 - 병사배치하기
<br>

#### 🗨 해결방법 
- dp인 것은 인지했지만 정확한 해결 방안이 떠오르지 않았음
- 열외해야하는 병사에 집중하기보다는 오름차순으로 최대의 길이를 구하도록 하는 것이 포인트인 문제였다,, 
<br>

## 🎈boj 2624 - 동전 바꿔주기
<br>

#### 🗨 해결방법 
- 모든 경우를 다 탐색해야겠다는 생각으로 구현하려 했으나 구현하지 못했습니다.
- 검색을 해보고 구현해보았지만 명확한 이해가 되지 않은 상태입니다🥲  
<br>

2023-08-17 13:36 UTC, devjy39 requested changes
## 동전 바꿔주기
- 동전을 하나 씩 보면서, 그 동전으로 1원 ~ 가격 까지 만들 수 있는 경우의 수를 모두 저장하는 배열을 만든다고 생각하고 풀어봅시다!
그럼 배열은 동전의 개수 x 가격 만큼 생성되겠죠??

### long 판단
- 저는 보통 n의 범위를 보고 최대값을 넣어봤을 때 답이 몇까지 커질 수 있을까? 를 보는편입니다.
- 근데 크리보드 문제의 경우 그렇게 판단하기 쉽지 않습니다, 하지만 n의 범위가 100까지밖에 되지 않기에 1 ~ 100까지 답을 다 출력해보면 오버플로가 발생하는지 바로 확인이 가능했습니다.
- 결론은 1. 범위로 확인 2. 큰 수 넣고 답 출력해보기 요정도면 될 것 같습니다.

2023-08-17 13:36 UTC, devjy39 commented on KimMiSeo/BOJ/BOJ7795_먹을것인가먹힐것인가.java
> +				for (int k=index-1; k>=0; k--) {
같은 수 일경우 쭉 탐색하는 방식으로 하셨군요!
하지만 이렇게 될 경우 찾아야하는 중복 수가 n개가 될 경우  전부 탐색해야할 수도 있어요
rower bound 라고하는 이진탐색을 직접 구현해봅시당
Arrays의 이진탐색은 중복 수가 있을 때는 사용하기 애매한 것 같아요

2023-08-17 13:36 UTC, devjy39 commented on KimMiSeo/BOJ/BOJ16401_과자나눠주기.java
> +		int end = snacks[n-1];
max 값을 구하기 위해 sort를 한 것으로 보이는데, 맞나요? 그렇다면 비용이 너무 클 것 같아요!

2023-08-17 14:38 UTC, sohy19 approved these changes

2023-08-18 10:11 UTC, seomiii commented on KimMiSeo/BOJ/BOJ7795_먹을것인가먹힐것인가.java
> +				for (int k=index-1; k>=0; k--) {
아하 얼마전에 해당내용을 읽은 적이있었는데!! 원하는 값 k 이상이 처음 나오는 위치를 찾아주는 lower bound를 사용하면 중복수를 처리해주지 않아도 되겠네요!!! 항상 좋은 인사이트 주셔서 감사합니다 짱재열님~!~!

2023-08-18 10:13 UTC, seomiii commented on KimMiSeo/BOJ/BOJ16401_과자나눠주기.java
> +		int end = snacks[n-1];
max값을 찾기 위해서 sort한 것 맞습니다! 정렬을 사용하지 않고 배열을 입력받을 때 max값을 구하면 비용을 줄일 수 있을 것같네요🤔

2023-08-18 11:31 UTC, devjy39 approved these changes

2023-08-19 03:41 UTC, devjy39 commented on KimMiSeo/BOJ/BOJ11058_크리보드.java
> +			for (int j=i, index=2; j<=n; j++, index++) { // i-3을 가지고 계속 복사하는 상황
오,, for문을 이렇게도 쓸 수 있군요.  

ps. 결국에 문제를 푸시는 게 의지와 습득력이 남다르신 것 같아요 ദ്ദി*ˊᗜˋ*)
문서화도 항상 되게 잘하셔서 보기 편한 것 같아요.

2023-08-19 12:53 UTC, merged